name: kounafoni CI pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    types:
      - closed

jobs:
  lint:
    runs-on: ubuntu-22.04

#    env:
#      POETRY_HOME: ${{ runner.temp }}/.poetry
#      PATH: ${{ runner.temp }}/.poetry/bin:${{ env.PATH }}

    steps:
      - name: Checking code availability
        uses: actions/checkout@v2

      - name: Install poetry and other external dependencies
        run: |
          sudo apt update -y
          sudo apt install -y pipx
          pipx install poetry==1.7.1
          export PATH="/root/.local/bin:$PATH"
#          apt install -y ffmpeg
#          rm -rf /var/lib/apt/lists/*


      - name: Install dependencies with poetry
        run: poetry install --no-root --no-cache --without explo
          
      - name: Black file formatting
        run: poetry run black --check .

      - name: Isort checking
        run: poetry run isort --check .
