name: Process ORTM News to audio summary

#on:
#  schedule:
#    # Set execution hour and minutes in UTC (a.k.a GMT)
#    - cron: '30 05 * * *'

on:
  push:
    branches:
      - '**'

jobs:
  process_audio:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository and code validity
      uses: actions/checkout@v4

    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh


    - name: Serve and pull ollama model
      run: |
        ollama serve &
        ollama pull mayflowergmbh/occiglot-7b-fr-en-instruct:latest

    - name: Install poetry
      run: |
        sudo apt update -y
        sudo apt install -y pipx ffmpeg jq openvpn
        pipx install poetry==1.7.1
        export PATH="/root/.local/bin:$PATH"

    - name: Install dependencies with poetry
      run: poetry install --no-root --no-cache --only main,news_processing

    - name: Enable VPN connection
      run: |
        # Get secrets
        echo "${{ secrets.OPENVPN_USERNAME }}" > openvpn_credentials.txt
        echo "${{ secrets.OPENVPN_PASSWORD }}" >> openvpn_credentials.txt
        
        # Get config
        echo "${{ secrets.OVPN_CONFIG }}" > nl-free-150.protonvpn.tcp.ovpn
        
        sudo openvpn --config nl-free-150.protonvpn.tcp.ovpn --auth-user-pass openvpn_credentials.txt --daemon

    # Get the last video in the playlist
    - name: Get the latest video id in the playlist
      id: get_video
      run: |
       poetry run yt-dlp --version
        
       # white cookie in a file
       echo  "${{ secrets.YT_DLP_COOKIE_EXTRACT }}" > yt_dlp_cookie_extract.txt
        
       # playlist url
       PLAYLIST_URL="https://youtube.com/playlist?list=PLDBQmURq6pOfBKc6WU0wXTg2vxAjxjQel&si=n9iNX7AUi-SpNN_N"
       
       # Search for the latest video inside the playlist
       VIDEO_ID=$(poetry run yt-dlp -Uv --cookies yt_dlp_cookie_extract.txt --flat-playlist -J "$PLAYLIST_URL" | jq -r '.entries[-176].id')
       if [ -z "$VIDEO_ID" ]; then
         echo "No video found in the playlist."
         exit 1
       fi
       
       # Save VIDEO_ID to environment file
       echo "VIDEO_ID=$VIDEO_ID" >> $GITHUB_ENV
       echo $VIDEO_ID

    # Download the audio in MP3 format
    - name: Download audio
      run: |
       # Get relevant attributes (id, upload_date and title) of the video
       VIDEO_ID="${{ steps.get_video.outputs.video_id }}"
       echo $VIDEO_ID
       echo ${{ steps.get_video.outputs.video_id }}
       
       EXTRACTED_DATE=$(poetry run yt-dlp --cookies yt_dlp_cookie_extract.txt --print upload_date "https://www.youtube.com/watch?v=${{ env.VIDEO_ID }}")
       UPLOAD_DATE=${EXTRACTED_DATE:0:4}-${EXTRACTED_DATE:4:2}-${EXTRACTED_DATE:6:2}
    
       echo $UPLOAD_DATE
       
       TITLE=$(poetry run yt-dlp -Uv --cookies yt_dlp_cookie_extract.txt --simulate --print "%(title)s" "https://www.youtube.com/watch?v=${{ env.VIDEO_ID }}")
       echo $TITLE
        
       # Donwload video as mp3 file
       poetry run yt-dlp -Uv --cookies yt_dlp_cookie_extract.txt -x --audio-format mp3 --audio-quality 192K "https://www.youtube.com/watch?v=${{ env.VIDEO_ID }}" -o "data/whisper/stt_audio/$UPLOAD_DATE/$TITLE.mp3"

    - name: Disable VPN connection
      run: sudo killall openvpn

    - name: Build Text To Speech (TTS), summarize and Speech To Text (STT)
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      # Launch the script to build the new summary audio
      run: poetry run python src/ortm_jt_audio_updater.py

    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Upload extracted texts from audio
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'data/whisper/stt_texts'
        destination: 'kounafonia-news/data'
        gzip: false # disable gzip compression on upload
        process_gcloudignore: false #no .gcloudignore file in the repo

    - name: Upload intro and body text splits
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'data/piper/split_texts/'
        destination: 'kounafonia-news/data'
        gzip: false # disable gzip compression on upload
        process_gcloudignore: false #no .gcloudignore file in the repo

    - name: Upload summarized texts from stt texts
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'data/whisper/summarized_texts'
        destination: 'kounafonia-news/data'
        gzip: false # disable gzip compression on upload
        process_gcloudignore: false #no .gcloudignore file in the repo

    - name: Upload summarized audio
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'data/piper/exports'
        destination: 'kounafonia-news/data'
        gzip: false # disable gzip compression on upload
        process_gcloudignore: false #no .gcloudignore file in the repo
