name: Update Vector Store

# on:
#   schedule:
#     # Set execution hour and minutes in UTC (a.k.a GMT)
#     - cron: '00 18 * * *'
on:
  push:
    branches:
      - '**'

jobs:
  compute_new_vectors:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository and code validity
      uses: actions/checkout@v4

    
    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}


    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'


    - name: Download articles and vector_store from GCS
      run: |
        mkdir -p data/articles
        gsutil -m cp -r gs://kounafonia-news/data/articles/malijet/2024/01 ./data/articles/malijet/2024/01

        mkdir -p data/vector_stores
        gsutil -m cp -r gs://kounafonia-news/data/vector_stores ./data/vector_stores


    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh

    
    - name: Serve and pull ollama model
      run: |
        ollama serve &
        ollama pull bge-m3:567m-fp16


    - name: Install poetry
      run: |
        sudo apt update -y
        sudo apt install -y pipx
        pipx install poetry==1.7.1
        export PATH="/root/.local/bin:$PATH"


    - name: Install dependencies with poetry
      run: poetry install --no-root --no-cache --only main,news_processing

    
    - name: Build new article vectors from embedding and store to vector store
      run: ls && ls -la && poetry run python src/chroma_db_updater.py


    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'data/vector_stores'
        destination: 'kounafonia-news'
        process_gcloudignore: false #no .gcloudignore file in the repo
